### ISSUE TITLE
yarn create @lukesheard/esbuild-app my-app fails with Yarn 3.1.1

### ISSUE THREAD

**Issue by inlightmedia** [LukeSheard/esbuild-scripts#131]
Trying to install with the latest version of yarn (3.1.1) fails with the following output:

➜  esbuild-test git:(master) ✗ yarn create @lukesheard/esbuild-app my-app
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 633ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ color-convert@npm:2.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ color-name@npm:1.1.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ commander@npm:8.3.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ has-flag@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ supports-color@npm:7.2.0 can't be found in the cache and will be fetched from the remote registr
➤ YN0000: └ Completed in 0s 452ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 1s 125ms

/private/var/folders/8n/sfkfwcld6hbfnnd2mtz4z58c0000gn/T/xfs-ae7701d8/dlx-91384/.pnp.cjs:9789
    throw firstError;
    ^

Error: @lukesheard/create-esbuild-app tried to access create-react-app, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: create-react-app
Required by: @lukesheard/create-esbuild-app@npm:1.0.0 (via /Users/home/.yarn/berry/cache/@lukesheard-create-esbuild-app-npm-1.0.0-1407c85c4b-8.zip/node_modules/@lukesheard/create-esbuild-app/)

Require stack:
- /Users/home/.yarn/berry/cache/@lukesheard-create-esbuild-app-npm-1.0.0-1407c85c4b-8.zip/node_modules/@lukesheard/create-esbuild-app/index.js
    at Function.external_module_.Module._resolveFilename (/private/var/folders/8n/sfkfwcld6hbfnnd2mtz4z58c0000gn/T/xfs-ae7701d8/dlx-91384/.pnp.cjs:9788:55)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/Users/home/.yarn/berry/cache/@lukesheard-create-esbuild-app-npm-1.0.0-1407c85c4b-8.zip/node_modules/@lukesheard/create-esbuild-app/index.js:23:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/private/var/folders/8n/sfkfwcld6hbfnnd2mtz4z58c0000gn/T/xfs-ae7701d8/dlx-91384/.pnp.cjs:9637:14)
    at Function.moduleExports.runMain (/private/var/folders/8n/sfkfwcld6hbfnnd2mtz4z58c0000gn/T/xfs-ae7701d8/dlx-91384/.pnp.cjs:9838:31)
    at node:internal/main/run_main_module:17:47

**Comment by LukeSheard** [comment]
Hey @inlightmedia I've released a new version of the CLI which should have fixed these issues now, let me know if they work or not. I'll try and add some tests for different versions of yarn as my toolchain is still running `yarn@1.x` at the moment!
